/* Autogenerated by png2wx.pl on Mon Jan 13 19:23:13 2014 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_watchdog;

#ifdef PLUGIN_USE_SVG
extern wxString _svg_watchdog;
//extern wxString _svg_watchdog_rollover;
extern wxString _svg_watchdog_toggled;
#endif

#endif /* ICONS_H */
