/* Autogenerated by png2wx.pl on Mon Jan 13 19:23:13 2014 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_watchdog;

#endif /* ICONS_H */
